module.exports = {
  content: ["./src/main/resources/templates/**/*.{html,js}"],
  theme: {
    colors: {
      'super-blue-lightest': '#E3F2FD',
      'super-blue-light': '#8ECAFB',
      'super-blue': '#0076d6',
      'super-blue-dark': '#175EA1',
      'super-blue-darkest': '#003662',
      'leafy-green-lightest': '#E5F4EA',
      'leafy-green-light': '#97D3AB',
      'leafy-green': '#028844',
      'leafy-green-dark': '#005826',
      'leafy-green-darkest': '#003119',
      'poppy-red-lightest': '#FFEAEC',
      'poppy-red-light': '#F09491',
      'poppy-red': '#E22922',
      'poppy-red-dark': '#B50005',
      'poppy-red-darkest': '#671210',
      'dandelion-yellow-lightest': "#FDF8C6",
      'dandelion-yellow-light': "#FFEF67",
      'dandelion-yellow': "#FFD500",
      'black': '#000000',
      'charcoal': '#333333',
      'battleship-grey': '#575757',
      'taupe-grey': '#929292',
      'platinum': '#E3E3E3',
      'white-smoke': '#F6F6F6',
      'white': '#FFFFFF'
    },
    extend: {},
  },
  plugins: [],
}
